apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: "2025.12.*"
      helm:
        releaseName: authentik
        parameters:
          - name: domain
            value: "authentik.piron-tech.com"
          - name: disableBootstrapUser
            value: "true"
          - name: postgresql.enabled
            value: "true"
          - name: postgresql.auth.existingSecret
            value: "authentik-postgresql"
          - name: redis.enabled
            value: "true"
          - name: redis.auth.existingSecret
            value: "authentik-redis"
          - name: server.replicas
            value: "2"
          - name: worker.replicas
            value: "1"
          - name: service.type
            value: "ClusterIP"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

