apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  sources:
    - repoURL: https://github.com/PierreH2/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: "2025.12.3"
      helm:
        releaseName: authentik
        valueFiles:
          - $values/namespaces-apps/authentik/values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

