apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PierreH2/homelab.git
    targetRevision: main
    path: namespaces-apps/plex/plex

  destination:
    server: https://kubernetes.default.svc
    namespace: plex

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
