apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

secretGenerator:
  - name: piron-homelab-ca
    type: kubernetes.io/tls
    files:
      - tls.crt=piron-homelab-ca.crt
      - tls.key=piron-homelab-ca.key

generatorOptions:
  disableNameSuffixHash: true
