apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-nas-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  hostPath:
    path: "/data/nas/private/keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-nas-pvc
  namespace: keycloak
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  volumeName: keycloak-nas-pv