apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner
  namespace: actions
spec:
  template:
    spec:
      serviceAccountName: github-runner-sa
      repository: PierreH2/homelab
      labels:
        - homelab-self-hosted