image:
  repository: ghcr.io/linuxserver/plex
  tag: latest

env:
  TZ: Europe/Paris
  PLEX_CLAIM: claim-sh4ePKGZEEBGz4B7eH2J


service:
  type: ClusterIP
  port: 32400

paths:
  config: /data/nas/public/plex/config
  media: /data/nas/public/plex/media

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

nodeSelector: {}

ingress:
  enabled: true
  hostname: plex.piron-tech.com

gateway:
  name: eg
  namespace: envoy-gateway-system
